# Generated by Django 5.1.2 on 2024-11-23 21:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='confirmed_booking',
            name='booking_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.CreateModel(
            name='Booking_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CPP', 'C++'), ('JA', 'JAVA'), ('PY', 'PYTHON'), ('DJ', 'DJANGO')], max_length=3)),
                ('confirmed', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='tutorials.student')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='confirmed_booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='confirmed_booking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_booking', to='tutorials.booking_requests'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmed_booking',
            unique_together={('booking', 'tutor', 'booking_date', 'booking_time')},
        ),
        migrations.DeleteModel(
            name='Pending_booking',
        ),
    ]
