# Generated by Django 5.1.2 on 2024-12-02 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending_booking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pending_booking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_to_learn',
        ),
        migrations.AddField(
            model_name='confirmed_booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='confirmed_booking',
            name='booking_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_days',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='MON', max_length=3),
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_times',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening'), (4, 'Morning and Afternoon'), (5, 'Afternoon and Evening'), (6, 'Morning and Evening'), (7, 'Whole day')], default=1),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='skills',
            field=models.CharField(choices=[('CPP', 'C++'), ('JA', 'Java'), ('PY', 'Python'), ('DJ', 'Django')], default=None, max_length=3),
        ),
        migrations.CreateModel(
            name='Booking_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CPP', 'C++'), ('JA', 'Java'), ('PY', 'Python'), ('DJ', 'Django')], max_length=3)),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='tutorials.student')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='confirmed_booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='confirmed_booking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_booking', to='tutorials.booking_requests'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmed_booking',
            unique_together={('booking', 'tutor', 'booking_date', 'booking_time')},
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Pending_booking',
        ),
    ]
