# Generated by Django 5.1.3 on 2024-11-20 17:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_to_learn",
                    models.CharField(
                        choices=[
                            ("CPP", "C++"),
                            ("JA", "JAVA"),
                            ("PY", "PYTHON"),
                            ("DJ", "DJANGO"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("tutorials.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        choices=[
                            ("CPP", "C++"),
                            ("JA", "JAVA"),
                            ("PY", "PYTHON"),
                            ("DJ", "DJANGO"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "experience_level",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("tutorials.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Pending_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("CPP", "C++"),
                            ("JA", "JAVA"),
                            ("PY", "PYTHON"),
                            ("DJ", "DJANGO"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_bookings",
                        to="tutorials.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "booking_date", "booking_time")},
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_day",
                    models.CharField(
                        choices=[
                            ("SUN", "Sunday"),
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "available_time",
                    models.IntegerField(
                        choices=[
                            (1, "Morning"),
                            (2, "Afternoon"),
                            (3, "Evening"),
                            (4, "Morning and Afternoon"),
                            (5, "Afternoon and Evening"),
                            (6, "Morning and Evening"),
                            (7, "Whole day"),
                        ]
                    ),
                ),
                (
                    "tutor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutorials.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Confirmed_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_booking",
                        to="tutorials.pending_booking",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_bookings",
                        to="tutorials.tutor",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "tutor")},
            },
        ),
    ]
