# Generated by Django 5.1.2 on 2024-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_confirmed_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_requests',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='booking_requests',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
