# Generated by Django 5.1.2 on 2024-11-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0002_student_tutor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="availableDays",
        ),
        migrations.RemoveField(
            model_name="student",
            name="availableTime",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="availableDays",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="availableTime",
        ),
        migrations.AddField(
            model_name="student",
            name="difficulty_level",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=None
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="experience_level",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=None
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="skills",
            field=models.CharField(
                choices=[
                    ("CPP", "C++"),
                    ("JA", "JAVA"),
                    ("PY", "PYTHON"),
                    ("DJ", "DJANGO"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_day",
                    models.CharField(
                        choices=[
                            ("SUN", "Sunday"),
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "available_time",
                    models.IntegerField(
                        choices=[
                            (1, "Morning"),
                            (2, "Afternoon"),
                            (3, "Evening"),
                            (4, "Morning and Afternoon"),
                            (5, "Afternoon and Evening"),
                            (6, "Morning and Evening"),
                            (7, "Whole day"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "tutor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutorials.tutor",
                    ),
                ),
            ],
        ),
    ]
