# Generated by Django 5.1.2 on 2024-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_booking_requests_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_to_learn',
        ),
        migrations.AddField(
            model_name='booking_requests',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None),
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_days',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_times',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening'), (4, 'Morning and Afternoon'), (5, 'Afternoon and Evening'), (6, 'Morning and Evening'), (7, 'Whole day')], default=None),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
