# Generated by Django 5.1.3 on 2024-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0003_remove_student_availabledays_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="available_time",
            field=models.IntegerField(
                choices=[
                    (1, "Morning"),
                    (2, "Afternoon"),
                    (3, "Evening"),
                    (4, "Morning and Afternoon"),
                    (5, "Afternoon and Evening"),
                    (6, "Morning and Evening"),
                    (7, "Whole day"),
                ]
            ),
        ),
    ]
