# Generated by Django 5.1.2 on 2024-11-14 14:46

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='tutorials.student')),
            ],
            options={
                'unique_together': {('student', 'booking_date', 'booking_time')},
            },
        ),
        migrations.CreateModel(
            name='Confirmed_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_booking', to='tutorials.pending_booking')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_bookings', to='tutorials.tutor')),
            ],
            options={
                'unique_together': {('booking', 'tutor')},
            },
        ),
    ]
