# Generated by Django 5.1.2 on 2024-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_pending_booking_confirmed_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_booking',
            name='subject',
            field=models.CharField(choices=[('CPP', 'C++'), ('JA', 'JAVA'), ('PY', 'PYTHON'), ('DJ', 'DJANGO')], default='CPP', max_length=3),
            preserve_default=False,
        ),
    ]
