# Generated by Django 5.1.3 on 2024-11-20 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0002_student_tutor_pending_booking_confirmed_booking"),
        ("tutorials", "0004_alter_availability_available_time"),
    ]

    operations = []
