# Generated by Django 5.1.3 on 2024-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0005_merge_20241120_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="difficulty_level",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=None
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="skill_to_learn",
            field=models.CharField(
                choices=[
                    ("CPP", "C++"),
                    ("JA", "JAVA"),
                    ("PY", "PYTHON"),
                    ("DJ", "DJANGO"),
                ],
                default=None,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="experience_level",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=None
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="skills",
            field=models.CharField(
                choices=[
                    ("CPP", "C++"),
                    ("JA", "JAVA"),
                    ("PY", "PYTHON"),
                    ("DJ", "DJANGO"),
                ],
                default=None,
                max_length=3,
            ),
        ),
    ]
